import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
const directory=path.resolve('../docs');
const context=await browser.newContext({viewport:{width:1440,height:1200},recordVideo:{dir:path.resolve('../data/demo-video'),size:{width:1440,height:1200}}});
const page=await context.newPage();
await page.goto('http://127.0.0.1:8000');
await page.getByRole('button',{name:'Run experiment →'}).click();
await page.waitForFunction(()=>parseFloat(document.querySelector('.clock')?.textContent||'0')>=55,null,{timeout:30000});
await page.getByRole('button',{name:'Pause',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.status')?.textContent==='PAUSED');
await page.screenshot({path:path.join(directory,'demo.png'),fullPage:true});
await page.waitForTimeout(500);
await page.getByRole('button',{name:'Resume',exact:true}).click();
await page.waitForTimeout(500);
await page.getByRole('button',{name:'End run',exact:true}).click();
await page.waitForTimeout(300);
const video=page.video();
await context.close();
await video.saveAs(path.join(directory,'demo.webm'));
await browser.close();
console.log('Saved docs/demo.png and docs/demo.webm');
